### ISSUE TITLE
I can't check your source code

### ISSUE THREAD

**Issue by lovetrading10** [iAhsanJaved/InstagramUsernameTaker#1]
I have changed the username and password in config.json with my Instagram account but it doesn't work.
The source code has the following error.
##############################
hjdhjhjdhx6h
[hjdhjhjdhx6h] is available!!!
[hjdhjhjdhx6h] Completed Turbo Killing Thread
**Login error! Check your login data!**
###############################
username and password are correct.
What did I forget to insert for it?
I will wait for your quick and favorable reply.

**Comment by HamzaAnis** [comment]
> I have changed the username and password in config.json with my Instagram account but it doesn't work.
> The source code has the following error.
> ##############################
> hjdhjhjdhx6h
> [hjdhjhjdhx6h] is available!!!
> [hjdhjhjdhx6h] Completed Turbo Killing Thread
> **Login error! Check your login data!**
> ###############################
> username and password are correct.
> What did I forget to insert for it?
> I will wait for your quick and favorable reply.

@SunHxiao I am not sure if it working at this moment but for this error you need to set your IG username and password in [config.json](https://github.com/iAhsanJaved/InstagramUsernameTaker/blob/master/config.json) on which you want the acquire the username written in the [usernames_list.txt](https://github.com/iAhsanJaved/InstagramUsernameTaker/blob/master/usernames_list.txt)
